// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBevg6VCwUCXZrlnR_OJ2UZs9VgNx4qiGY',
    appId: '1:1086011415941:web:04d25f52787809aa7538ec',
    messagingSenderId: '1086011415941',
    projectId: 'rj-project-9ae32',
    authDomain: 'rj-project-9ae32.firebaseapp.com',
    storageBucket: 'rj-project-9ae32.appspot.com',
    measurementId: 'G-8JJJ21W9PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgwnhGqllUwNWb1A7kMy-VcDgDHkh3Uak',
    appId: '1:1086011415941:android:7cb25f26120cf4787538ec',
    messagingSenderId: '1086011415941',
    projectId: 'rj-project-9ae32',
    storageBucket: 'rj-project-9ae32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyU1EgZkyQCOMPnm4N8DpheJzVDFE0boc',
    appId: '1:1086011415941:ios:b6ee105c4abdd5137538ec',
    messagingSenderId: '1086011415941',
    projectId: 'rj-project-9ae32',
    storageBucket: 'rj-project-9ae32.appspot.com',
    iosClientId: '1086011415941-na0g6lam66iltkigblq32fqrknin9i0n.apps.googleusercontent.com',
    iosBundleId: 'com.rj.project',
  );
}
